### PR TITLE
Kicking the tires

### PR DESCRIPTION
**Pull request by timholy**
Hi Andy & Chris,

I finally got around to giving this a try. Overall it looks really promising, but just copying examples from the README I had troubles getting things to work on either julia 0.4 or 0.5. At least for julia 0.5 it turned out to be just a small number of details, fortunately, and this PR at least gets the basics working for me. (On 0.4 I get some kind of parsing error that I didn't look into.)

The last commit in this series was a more speculative change (requiring julia 0.5) taking the first steps towards an `@generated`-free implementation, which I suspect might be necessary to get this accepted into Base. Based on the comments below I now think that was a premature step, so I'd be happy to drop the final commit.

There are a couple of issues I see:
- the new `runtests.jl` illustrates (see the comment about "throws") what I see as the most serious problem: more specific argument type specifications "throw out" any trait-dispatch you've defined for less specific argument types. 
- each time you define a trait you get a "method overwritten" warning on 0.5. Presumably one could fix it by making definition of the generated function conditional on a signature comparison with `methods(f, types)`. However, the strategy here might depend on how we resolve the first point.

In terms of solving the first problem, one possible strategy might be:

``` jl
abstract Size
immutable Big <: Size; end
immutable Medium <: Size; end
immutable Small <: Size; end
# Note I'm using instances on the RHS
Size(::Union{Type{Int32},Type{Int64}}) = Small()
Size(::Type{BigInt}) = Big()
Size(::Type{Int128}) = Medium()

# This function is defined by @traitor foo(x::::Big)
foo(x) = _foo((x,Size(typeof(x))))
function _foo(x_trait::Tuple{Any,Big})
    x = x_trait[1]
    "Huge!"
end

# This function is defined by @traitor foo(x::Integer::Small)
foo(x::Integer) = _foo((x,Size(typeof(x))))
function _foo(x_trait::Tuple{Integer,Small})
    x = x_trait[1]
    "Teensy..."
end

julia> foo(1)
"Teensy..."

julia> foo(BigInt(3))
"Huge!"
```

That's a pretty big redesign, of course, and one risk is that we'd end up with difficult-to-resolve method ambiguities. I'd be curious to know your thoughts.

### CODE REVIEW

**Comment by timholy** [comment]
One challenge for this strategy is: what happens if you have two different trait-families that you want to dispatch on? I don't currently have a fix for that, but I'll think about it.

**Comment by andyferris** [comment]
Hi Tim,

Thanks for taking a look, and fixing up these problems! I swear this _was_ working on an older version of 0.5 nightlies, Oh well, it seems to be now picky about the order of the function definitions. I don't think we specifically targeted 0.4, but it may be possible to get it working there too.

Unfortunately, I don't have a lot of time right now (I will check again in the morning), but what I saw in this PR so far looked great. Some quick responses to your comments:

> the new runtests.jl illustrates (see the comment about "throws") what I see as the most serious problem: more specific argument type specifications "throw out" any trait-dispatch you've defined for less specific argument types.

So the current design is really that standard multiple dispatch occurs first to select a method, and trait dispatch occurs second to select a "submethod", so to me I'm not surprised by the behaviour you saw. Not that I'm saying the current design is optimal, but some changes would have to be made to support more general dispatch problems.

I think to do it "properly" we should try to own method dispatch too. So we could have a single thunk for the entire function, and keep our own method table with both standard signatures and trait signatures. I agree that solving this problem seems really important to make it more natural and useful. :) It would even allow us to address default arguments and keyword arguments in a complete manner (the complication being we have to implement all the rules of Julia dispatch in our generated thunk). In this case, I think we should determine "more specific" between matching signatures by having it dominated by standard type-based dispatch and then use traits when there are multiple identical (standard) matching signatures. Does this make sense?

> each time you define a trait you get a "method overwritten" warning on 0.5. Presumably one could fix it by making definition of the generated function conditional on a signature comparison with methods(f, types). However, the strategy here might depend on how we resolve the first point.

Yes, great idea! The warnings are annoying. Another way might be to see if `get_trait_table()` returns an empty table and only define the thunk if it is.

Finally, I'm not sure if we can really get rid of the `@generated` function for the thunk. Maybe we can... but as far as I could tell, if you don't know in advance how many traits will be defined in a given method, or which trait classes they might belong to, then its really difficult to write a single thunk that is compatible with all (including future definitions of submethods). After we tried several times, I felt that single-inheritance multiple-dispatch was somehow _incompatible_ with multiple-inheritance traits. 

The one possibility I thought of so-far of skipping the `@generated` functions might be to do something like what `@betray` is supposed to do: take all the existing methods and redefine them in some way compatible with all the trait classes defined to-date. Though, I'm not certain of the specifics of this idea yet...

**Comment by timholy** [comment]
I do think this is a consistent strategy. I am having a hard time guessing in advance whether I'd want this or a more "symmetric" form. Might just have to try and see.

As far as doing all this in a generated-free form, I can't see ahead to a solution yet either, other than to say all the ways that I use traits now don't require `@generated` functions. The package I'm most interested in using these for is a new effort, [ImagesAxes](https://github.com/JuliaImages/ImagesAxes.jl). See in particular the [Temporal axes](https://github.com/JuliaImages/ImagesAxes.jl/blob/master/docs/build/index.md#temporal-axes) portion of the docs. Right now it's a tiny package (<100 loc, including comments about Traitor in both src and test), so might be interesting food for thought.

**Comment by andyferris** [comment]
_ImageAxes_ (and _AxisArrays_) seem really cool! :)

> I do think this is a consistent strategy. I am having a hard time guessing in advance whether I'd want this or a more "symmetric" form. Might just have to try and see.

Yes, this is probably correct. However, you are right that we should be able to define:

``` julia
@traitor function howbig(x::Any::Big)
@traitor function howbig(x::::Medium)
@traitor function howbig(x::Integer::Small)
```

This shouldn't be an "ambiguity error" in standard multiple dispatch terms. We can think that one of the traits of `x` is its type, here we have definitions for `Any` and `Integer`. Another is its `Size`. The third definition is more specific in both, and is therefore unambiguous.

So to do the full method lookup, I was thinking of using something like the `DataType` trait for the standard dispatch part. We already have `DataType(Int64) = Int64`, `DataType(Tuple{}) = Tuple{}`, etc, for all concrete types (AFAICT). So we take the thing after the first `::` (or else `Any`) as that method's `DataType` trait specification, and treat those after the second `::` exactly as we do now, and it _might_ all just work out (though I understand there might be some subtleties in Julia's current dispatch system).

> other than to say all the ways that I use traits now don't require `@generated` functions. 

Indeed. the THTT works perfectly well when you know in advance how many traits your function (or method, rather) will dispatch on. The `@generated` function is there to allow extra traits to be defined later, maybe in other packages not controlled by you, to specialize an existing method/function without overwriting any existing methods.

**Pull request merged**
